Fix verify publish ci
Step `Verify cargo publish includes all files needed to build` is
failing with:
```
error: crates-io is replaced with non-remote-registry source dir chrono-tz/vendor;
include `--registry crates-io` to use crates.io
```

The error appears only with cargo 1.82 and greater.

Passing `--registry crates-io` is not a solution because it a nightly-only option.

Calling `cargo publish -p <name>` for each crate solves the problem.